apiVersion: v1
kind: Service
metadata:
    name: capstone-app

spec:
    type: LoadBalancer
    selector:
        app: capstone-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
